### ISSUE TITLE
compiler errors on findtri program

### ISSUE THREAD

**Issue by o-dawgie** [xiazeqing/triwitch#1]
I was trying this program out for the seed of my own world, and the first program worked fine, but when compiling the second program with the command line compiler on macOS Mojave, it generated five errors which looked like this:
```main.cpp:25:9: error: use of undeclared identifier 'sqrt'; did you mean 'sqr'?
        return sqrt(sqrdist(l,r));
               ^~~~
               sqr
main.cpp:15:18: note: 'sqr' declared here
inline long long sqr(long long x) {
                 ^
main.cpp:30:9: error: use of undeclared identifier 'sqrt'; did you mean 'sqr'?
        return sqrt(p*(p - a)*(p - b)*(p - c));
               ^~~~
               sqr
main.cpp:15:18: note: 'sqr' declared here
inline long long sqr(long long x) {
                 ^
main.cpp:86:15: error: use of undeclared identifier 'sqrt'; did you mean 'sqr'?
                        double a = sqrt(sqrd);
                                   ^~~~
                                   sqr
main.cpp:15:18: note: 'sqr' declared here
inline long long sqr(long long x) {
                 ^
main.cpp:91:16: error: use of undeclared identifier 'sqrt'; did you mean 'sqr'?
                                double b = sqrt(sqrd);
                                           ^~~~
                                           sqr
main.cpp:15:18: note: 'sqr' declared here
inline long long sqr(long long x) {
                 ^
main.cpp:104:16: error: use of undeclared identifier 'sqrt'; did you mean 'sqr'?
                                double c = sqrt(sqrd);
                                           ^~~~
                                           sqr
main.cpp:15:18: note: 'sqr' declared here
inline long long sqr(long long x) {
                 ^
5 errors generated.
```

The command which I was using to compile looked like this:
`g++ main.cpp -o witchpt2`

I don't know if I've done something wrong or if maybe something has changed in the language, but I have a very limited understanding of c++ and coding in general (just starting to learn a bit), so I have had no success in trying to troubleshoot this problem myself. If you could offer any advice, it would be greatly appreciated. Thank you!

**Comment by xiazeqing** [comment]
Ahhhhhh... It should be an issue about Visual Studio, which automatically include some frequently used functions such as "sqrt" and "memset". (In Visual Studio, it is in xtgmath.h, which is automatically included; I also saw it in cmath and math.h. Maybe the latter is more widely used.)
Maybe you can try add the following line (sorry but I'm not familiar with macOS Compiler, I'm not sure if it works or not; if not, there must be somewhere else that contains the "sqrt" function)

> #include <math.h>

Sorry for your inconvenience!
