### ISSUE TITLE
How long does it take to find the Trihuts?

### ISSUE THREAD

**Issue by BaneRevenge** [xiazeqing/triwitch#3]
Hey, at first thank you for sharing your program. :D

I just have a simple question, how long does the program need to find the Trihuts?
The Trihutfinder is searching in my 100k file for nearly 3 days now. 

I tested the Trihutfinder with a 1000 chunk file to see if it works and I got instant the empty output file, so I think that i compiled the tool correctly.

Thanks for any help

**Comment by 63815af756f0357940c666d2ae1c801d** [comment]
It should depends on your CPU. 
I run the whole program on my i7-7700k@4.20GHz for overnight. 

P.S. Maybe you can try to splited the map area into -100k ~ -90k, -90k ~ -80k, ... 90k ~ 100k and run them parallelly for the witch/main.cpp, and each of them runs 1~3 hours.

But it shouldn't run for that much time... 
Maybe you can add some cout commands to show which step you have reached? 
Or paste your seed here to see if it runs correctly?
// Unfortunately, some seeds, such as the PKU minecraft server seed, do not have any tri-witch-hut within 1m chunk coordinates ---- which means 16m corrdinates in main world. Be prepared if some bad news happens.

**Comment by BaneRevenge** [comment]
Hm, it runs on an Intel i5-9600K.

> P.S. Maybe you can try to splited the map area into -100k ~ -90k, -90k ~ -80k, ... 90k ~ 100k and run them parallelly for the witch/main.cpp, and each of them runs 1~3 hours.

That's a good idea, I will try that, thanks.

My seed is: -5524766222678667265

**Comment by 63815af756f0357940c666d2ae1c801d** [comment]
> My seed is: -5524766222678667265

Bad News: Nothing found within 100k range.
Nearest 2-connected chunk coordinate are  -99263 98423 -99263 98432
which means -1588199 1574777 -1588199 1574921 ingame

I'm currently searching within 1m chunk coordinate.

**Comment by BaneRevenge** [comment]
Did you find anything?
The tool still runs on my server.
Idk what i did wrong.

**Comment by 63815af756f0357940c666d2ae1c801d** [comment]
> Did you find anything?
> The tool still runs on my server.
> Idk what i did wrong.

I found it, and you can stop it now.
the chunk coordinates are:
-712107 -820896 -712105 -820905 -712093 -820895
the in-game coordinates are:
-11393703 | -13134327 | -11393671 | -13134471 | -11393479 | -13134311

You can also check it in chunkbase.com:
![10k](https://user-images.githubusercontent.com/64824439/82107765-c4a2a400-975c-11ea-9d40-7d30c87480dc.PNG)

**Comment by BaneRevenge** [comment]
Thank you very much!
You're the best!
